// Code generated by "stringer -type=RequestEvent"; DO NOT EDIT.

package restrequest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RequestUpdateUrl-0]
	_ = x[RequestUpdateHeaders-1]
	_ = x[RequestUpdateMethod-2]
	_ = x[RequestUpdateQuery-3]
	_ = x[RequestUpdateBodyJson-4]
	_ = x[RequestUpdateBodyFormdata-5]
	_ = x[RequestUpdateScript-6]
	_ = x[RequestDelete-7]
	_ = x[RequestError-8]
}

const _RequestEvent_name = "RequestUpdateUrlRequestUpdateHeadersRequestUpdateMethodRequestUpdateQueryRequestUpdateBodyJsonRequestUpdateBodyFormdataRequestUpdateScriptRequestDeleteRequestError"

var _RequestEvent_index = [...]uint8{0, 16, 36, 55, 73, 94, 119, 138, 151, 163}

func (i RequestEvent) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RequestEvent_index)-1 {
		return "RequestEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RequestEvent_name[_RequestEvent_index[idx]:_RequestEvent_index[idx+1]]
}
