// Code generated by "stringer -type=RequestEvent"; DO NOT EDIT.

package restrequest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RequestUpdateUrl-0]
	_ = x[RequestUpdateHeaders-1]
	_ = x[RequestUpdateAuthorization-2]
	_ = x[RequestUpdateMethod-3]
	_ = x[RequestUpdateQuery-4]
	_ = x[RequestUpdateBodyJson-5]
	_ = x[RequestUpdateBodyFormdata-6]
	_ = x[RequestUpdateScript-7]
	_ = x[RequestDelete-8]
	_ = x[RequestError-9]
	_ = x[RequestSuccess-10]
}

const _RequestEvent_name = "RequestUpdateUrlRequestUpdateHeadersRequestUpdateAuthorizationRequestUpdateMethodRequestUpdateQueryRequestUpdateBodyJsonRequestUpdateBodyFormdataRequestUpdateScriptRequestDeleteRequestErrorRequestSuccess"

var _RequestEvent_index = [...]uint8{0, 16, 36, 62, 81, 99, 120, 145, 164, 177, 189, 203}

func (i RequestEvent) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RequestEvent_index)-1 {
		return "RequestEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RequestEvent_name[_RequestEvent_index[idx]:_RequestEvent_index[idx+1]]
}
