// Code generated by "stringer -type=RequestEvent"; DO NOT EDIT.

package restrequest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RequestUpdateUrl-0]
	_ = x[RequestUpdateHeaders-1]
	_ = x[RequestUpdateAuthorization-2]
	_ = x[RequestUpdateMethod-3]
	_ = x[RequestUpdateName-4]
	_ = x[RequestUpdateQuery-5]
	_ = x[RequestUpdateBodyJson-6]
	_ = x[RequestUpdateBodyFormdata-7]
	_ = x[RequestUpdateScript-8]
	_ = x[RequestDelete-9]
	_ = x[RequestError-10]
	_ = x[RequestSuccess-11]
}

const _RequestEvent_name = "RequestUpdateUrlRequestUpdateHeadersRequestUpdateAuthorizationRequestUpdateMethodRequestUpdateNameRequestUpdateQueryRequestUpdateBodyJsonRequestUpdateBodyFormdataRequestUpdateScriptRequestDeleteRequestErrorRequestSuccess"

var _RequestEvent_index = [...]uint8{0, 16, 36, 62, 81, 98, 116, 137, 162, 181, 194, 206, 220}

func (i RequestEvent) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RequestEvent_index)-1 {
		return "RequestEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RequestEvent_name[_RequestEvent_index[idx]:_RequestEvent_index[idx+1]]
}
